[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = true

[dependencies]
forge-std = "1.14.0"
"@openzeppelin-contracts" = "5.6.0-rc.0"
"@openzeppelin-contracts-upgradeable" = "5.6.0-rc.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
